enum NETWORK_STATUS {
	CONNECTED = "connected",
	WEAK = "weak",
	DISCONNECTED = "disconnected",
}

const MAX_PASSWORD_ATTEMPTS = 3;
const MAX_PACKETS = 1000;

export { MAX_PACKETS, MAX_PASSWORD_ATTEMPTS, NETWORK_STATUS };
